### ISSUE TITLE
url is messed up

### ISSUE THREAD

**Issue by CThuleHansen** [overturetool/intocps-tracability-driver#4]
`"url": "file:C:/Users/ctha/into-cps-projects/./case-study_single_watertank/45424fdac16a95efd2db477ce28f3444f61d42d4/Models/SingleWT/HardwareInterface.vdmrt",`

**Comment by lausdahl** [comment]
It looks like this example did not have a remote set. Can you try this command:

```bash
git config --get remote.origin.url
```

if nothing is returned then it defaults to local file path otherwise it decodes as github or gitlab (not yet implemented)
